version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./public:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data
